// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"sync"

	"go.opentelemetry.io/collector/pdata"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

// ExportPartialSuccess represents the details of a partially successful export request.
type LazyExportMetricsPartialSuccess struct {
	ExportMetricsPartialSuccess
	bytes []byte
}

var (
	protoPoolLazyExportMetricsPartialSuccess = sync.Pool{
		New: func() any {
			return &LazyExportMetricsPartialSuccess{}
		},
	}
)

func NewLazyExportMetricsPartialSuccess() *LazyExportMetricsPartialSuccess {
	if !UseProtoPooling.IsEnabled() {
		return &LazyExportMetricsPartialSuccess{}
	}
	return protoPoolLazyExportMetricsPartialSuccess.Get().(*LazyExportMetricsPartialSuccess)
}

func DeleteLazyExportMetricsPartialSuccess(orig *LazyExportMetricsPartialSuccess, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	DeleteExportMetricsPartialSuccess(&orig.ExportMetricsPartialSuccess, false)

	orig.Reset()
	if nullable {
		protoPoolLazyExportMetricsPartialSuccess.Put(orig)
	}
}

func CopyLazyExportMetricsPartialSuccess(dest, src *LazyExportMetricsPartialSuccess) *LazyExportMetricsPartialSuccess {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewLazyExportMetricsPartialSuccess()
	}

	CopyExportMetricsPartialSuccess(&dest.ExportMetricsPartialSuccess, &src.ExportMetricsPartialSuccess)
	dest.bytes = src.bytes

	return dest
}

func CopyLazyExportMetricsPartialSuccessSlice(dest, src []LazyExportMetricsPartialSuccess) []LazyExportMetricsPartialSuccess {
	var newDest []LazyExportMetricsPartialSuccess
	if cap(dest) < len(src) {
		newDest = make([]LazyExportMetricsPartialSuccess, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteLazyExportMetricsPartialSuccess(&dest[i], false)
		}
	}
	for i := range src {
		CopyLazyExportMetricsPartialSuccess(&newDest[i], &src[i])
	}
	return newDest
}

func CopyLazyExportMetricsPartialSuccessPtrSlice(dest, src []*LazyExportMetricsPartialSuccess) []*LazyExportMetricsPartialSuccess {
	var newDest []*LazyExportMetricsPartialSuccess
	if cap(dest) < len(src) {
		newDest = make([]*LazyExportMetricsPartialSuccess, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewLazyExportMetricsPartialSuccess()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteLazyExportMetricsPartialSuccess(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewLazyExportMetricsPartialSuccess()
		}
	}
	for i := range src {
		CopyLazyExportMetricsPartialSuccess(newDest[i], src[i])
	}
	return newDest
}

func (orig *LazyExportMetricsPartialSuccess) Reset() {
	*orig = LazyExportMetricsPartialSuccess{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *LazyExportMetricsPartialSuccess) MarshalJSON(dest *json.Stream) {
	orig.ExportMetricsPartialSuccess.MarshalJSON(dest)
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *LazyExportMetricsPartialSuccess) UnmarshalJSON(iter *json.Iterator) {
	orig.ExportMetricsPartialSuccess.UnmarshalJSON(iter)
}

func (orig *LazyExportMetricsPartialSuccess) SizeProto() int {
	return orig.ExportMetricsPartialSuccess.SizeProto()
}

func (orig *LazyExportMetricsPartialSuccess) MarshalProto(buf []byte) int {
	return orig.ExportMetricsPartialSuccess.MarshalProto(buf)
}

func (orig *LazyExportMetricsPartialSuccess) UnmarshalProto(buf []byte) error {
	return orig.UnmarshalProtoOpts(buf, &pdata.DefaultUnmarshalOptions)
}

func (orig *LazyExportMetricsPartialSuccess) UnmarshalProtoOpts(buf []byte, opts *pdata.UnmarshalOptions) error {
	if !opts.LazyDecoding {
		return orig.ExportMetricsPartialSuccess.UnmarshalProtoOpts(buf, opts)
	}
	if err := SkipExportMetricsPartialSuccessProto(buf); err != nil {
		return err
	}
	orig.bytes = buf
	orig.ExportMetricsPartialSuccess.Reset()
	return nil
}

func SkipLazyExportMetricsPartialSuccessProto(buf []byte) error {
	return SkipExportMetricsPartialSuccessProto(buf)
}

func (orig *LazyExportMetricsPartialSuccess) FinishUnmarshal(buf *ExportMetricsPartialSuccess) (*ExportMetricsPartialSuccess, error) {
	if len(orig.bytes) == 0 {
		return &orig.ExportMetricsPartialSuccess, nil
	}
	err := buf.UnmarshalProto(orig.bytes)
	return buf, err
}

func GenTestLazyExportMetricsPartialSuccess() *LazyExportMetricsPartialSuccess {
	orig := NewLazyExportMetricsPartialSuccess()
	orig.ExportMetricsPartialSuccess = *GenTestExportMetricsPartialSuccess()
	return orig
}

func GenTestLazyExportMetricsPartialSuccessPtrSlice() []*LazyExportMetricsPartialSuccess {
	orig := make([]*LazyExportMetricsPartialSuccess, 5)
	orig[0] = NewLazyExportMetricsPartialSuccess()
	orig[1] = GenTestLazyExportMetricsPartialSuccess()
	orig[2] = NewLazyExportMetricsPartialSuccess()
	orig[3] = GenTestLazyExportMetricsPartialSuccess()
	orig[4] = NewLazyExportMetricsPartialSuccess()
	return orig
}

func GenTestLazyExportMetricsPartialSuccessSlice() []LazyExportMetricsPartialSuccess {
	orig := make([]LazyExportMetricsPartialSuccess, 5)
	orig[1] = *GenTestLazyExportMetricsPartialSuccess()
	orig[3] = *GenTestLazyExportMetricsPartialSuccess()
	return orig
}
