// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/metadata"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

func (m *Metric) GetData() any {
	if m != nil {
		return m.Data
	}
	return nil
}

type Metric_Gauge struct {
	Gauge *Gauge
}

func (m *Metric) GetGauge() *Gauge {
	if v, ok := m.GetData().(*Metric_Gauge); ok {
		return v.Gauge
	}
	return nil
}

type Metric_Sum struct {
	Sum *Sum
}

func (m *Metric) GetSum() *Sum {
	if v, ok := m.GetData().(*Metric_Sum); ok {
		return v.Sum
	}
	return nil
}

type Metric_Histogram struct {
	Histogram *Histogram
}

func (m *Metric) GetHistogram() *Histogram {
	if v, ok := m.GetData().(*Metric_Histogram); ok {
		return v.Histogram
	}
	return nil
}

type Metric_ExponentialHistogram struct {
	ExponentialHistogram *ExponentialHistogram
}

func (m *Metric) GetExponentialHistogram() *ExponentialHistogram {
	if v, ok := m.GetData().(*Metric_ExponentialHistogram); ok {
		return v.ExponentialHistogram
	}
	return nil
}

type Metric_Summary struct {
	Summary *Summary
}

func (m *Metric) GetSummary() *Summary {
	if v, ok := m.GetData().(*Metric_Summary); ok {
		return v.Summary
	}
	return nil
}

// Metric represents one metric as a collection of datapoints.
// See Metric definition in OTLP: https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto
type Metric struct {
	Name        string
	Description string
	Unit        string
	Data        any
	Metadata    []KeyValue
}

func NewMetric() *Metric {
	return Alloc[Metric](nil)
}

func DeleteMetric(orig *Metric, nullable bool) {
	if orig == nil {
		return
	}

	if !metadata.PdataUseProtoPoolingFeatureGate.IsEnabled() {
		orig.Reset()
		return
	}

	switch ov := orig.Data.(type) {
	case *Metric_Gauge:
		DeleteGauge(ov.Gauge, true)
		ov.Gauge = nil
	case *Metric_Sum:
		DeleteSum(ov.Sum, true)
		ov.Sum = nil
	case *Metric_Histogram:
		DeleteHistogram(ov.Histogram, true)
		ov.Histogram = nil
	case *Metric_ExponentialHistogram:
		DeleteExponentialHistogram(ov.ExponentialHistogram, true)
		ov.ExponentialHistogram = nil
	case *Metric_Summary:
		DeleteSummary(ov.Summary, true)
		ov.Summary = nil
	}
	for i := range orig.Metadata {
		DeleteKeyValue(&orig.Metadata[i], false)
	}
	orig.Reset()
	_ = nullable
}

func CopyMetric(dest, src *Metric, st *State) *Metric {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = Alloc[Metric](st)
	}
	dest.Name = CopyString(st, src.Name)

	dest.Description = CopyString(st, src.Description)

	dest.Unit = CopyString(st, src.Unit)

	switch t := src.Data.(type) {
	case *Metric_Gauge:
		ov := Alloc[Metric_Gauge](st)
		ov.Gauge = Alloc[Gauge](st)
		CopyGauge(ov.Gauge, t.Gauge, st)
		dest.Data = ov

	case *Metric_Sum:
		ov := Alloc[Metric_Sum](st)
		ov.Sum = Alloc[Sum](st)
		CopySum(ov.Sum, t.Sum, st)
		dest.Data = ov

	case *Metric_Histogram:
		ov := Alloc[Metric_Histogram](st)
		ov.Histogram = Alloc[Histogram](st)
		CopyHistogram(ov.Histogram, t.Histogram, st)
		dest.Data = ov

	case *Metric_ExponentialHistogram:
		ov := Alloc[Metric_ExponentialHistogram](st)
		ov.ExponentialHistogram = Alloc[ExponentialHistogram](st)
		CopyExponentialHistogram(ov.ExponentialHistogram, t.ExponentialHistogram, st)
		dest.Data = ov

	case *Metric_Summary:
		ov := Alloc[Metric_Summary](st)
		ov.Summary = Alloc[Summary](st)
		CopySummary(ov.Summary, t.Summary, st)
		dest.Data = ov

	default:
		dest.Data = nil
	}
	dest.Metadata = CopyKeyValueSlice(dest.Metadata, src.Metadata, st)

	return dest
}

func CopyMetricSlice(dest, src []Metric, st *State) []Metric {
	var newDest []Metric
	if cap(dest) < len(src) {
		newDest = AllocSlice[Metric](st, len(src), len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteMetric(&dest[i], false)
		}
	}
	for i := range src {
		CopyMetric(&newDest[i], &src[i], st)
	}
	return newDest
}

func CopyMetricPtrSlice(dest, src []*Metric, st *State) []*Metric {
	var newDest []*Metric
	if cap(dest) < len(src) {
		newDest = AllocSlice[*Metric](st, len(src), len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = Alloc[Metric](st)
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteMetric(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = Alloc[Metric](st)
		}
	}
	for i := range src {
		CopyMetric(newDest[i], src[i], st)
	}
	return newDest
}

func (orig *Metric) Reset() {
	*orig = Metric{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *Metric) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	if orig.Name != "" {
		dest.WriteObjectField("name")
		dest.WriteString(orig.Name)
	}
	if orig.Description != "" {
		dest.WriteObjectField("description")
		dest.WriteString(orig.Description)
	}
	if orig.Unit != "" {
		dest.WriteObjectField("unit")
		dest.WriteString(orig.Unit)
	}
	switch orig := orig.Data.(type) {
	case *Metric_Gauge:
		if orig.Gauge != nil {
			dest.WriteObjectField("gauge")
			orig.Gauge.MarshalJSON(dest)
		}
	case *Metric_Sum:
		if orig.Sum != nil {
			dest.WriteObjectField("sum")
			orig.Sum.MarshalJSON(dest)
		}
	case *Metric_Histogram:
		if orig.Histogram != nil {
			dest.WriteObjectField("histogram")
			orig.Histogram.MarshalJSON(dest)
		}
	case *Metric_ExponentialHistogram:
		if orig.ExponentialHistogram != nil {
			dest.WriteObjectField("exponentialHistogram")
			orig.ExponentialHistogram.MarshalJSON(dest)
		}
	case *Metric_Summary:
		if orig.Summary != nil {
			dest.WriteObjectField("summary")
			orig.Summary.MarshalJSON(dest)
		}
	}
	if len(orig.Metadata) > 0 {
		dest.WriteObjectField("metadata")
		dest.WriteArrayStart()
		orig.Metadata[0].MarshalJSON(dest)
		for i := 1; i < len(orig.Metadata); i++ {
			dest.WriteMore()
			orig.Metadata[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *Metric) UnmarshalJSON(iter *json.Iterator) {
	orig.UnmarshalJSONState(iter, nil)
}

// UnmarshalJSONState unmarshals using st for nested allocations when an arena is attached.
func (orig *Metric) UnmarshalJSONState(iter *json.Iterator, st *State) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "name":

			orig.Name = CopyString(st, iter.ReadString())
		case "description":

			orig.Description = CopyString(st, iter.ReadString())
		case "unit":

			orig.Unit = CopyString(st, iter.ReadString())

		case "gauge":
			{
				ov := Alloc[Metric_Gauge](st)
				ov.Gauge = Alloc[Gauge](st)
				ov.Gauge.UnmarshalJSONState(iter, st)
				orig.Data = ov
			}
		case "sum":
			{
				ov := Alloc[Metric_Sum](st)
				ov.Sum = Alloc[Sum](st)
				ov.Sum.UnmarshalJSONState(iter, st)
				orig.Data = ov
			}
		case "histogram":
			{
				ov := Alloc[Metric_Histogram](st)
				ov.Histogram = Alloc[Histogram](st)
				ov.Histogram.UnmarshalJSONState(iter, st)
				orig.Data = ov
			}
		case "exponentialHistogram", "exponential_histogram":
			{
				ov := Alloc[Metric_ExponentialHistogram](st)
				ov.ExponentialHistogram = Alloc[ExponentialHistogram](st)
				ov.ExponentialHistogram.UnmarshalJSONState(iter, st)
				orig.Data = ov
			}
		case "summary":
			{
				ov := Alloc[Metric_Summary](st)
				ov.Summary = Alloc[Summary](st)
				ov.Summary.UnmarshalJSONState(iter, st)
				orig.Data = ov
			}

		case "metadata":
			for iter.ReadArray() {
				orig.Metadata = Append(st, orig.Metadata, KeyValue{})
				orig.Metadata[len(orig.Metadata)-1].UnmarshalJSONState(iter, st)
			}

		default:
			iter.HandleUnknownField(f)
		}
	}
}

func (orig *Metric) SizeProto() int {
	var n int
	var l int
	_ = l

	l = len(orig.Name)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}

	l = len(orig.Description)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}

	l = len(orig.Unit)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	switch orig := orig.Data.(type) {
	case nil:
		_ = orig
		break
	case *Metric_Gauge:
		if orig.Gauge != nil {
			l = orig.Gauge.SizeProto()
			n += 1 + proto.Sov(uint64(l)) + l
		}
	case *Metric_Sum:
		if orig.Sum != nil {
			l = orig.Sum.SizeProto()
			n += 1 + proto.Sov(uint64(l)) + l
		}
	case *Metric_Histogram:
		if orig.Histogram != nil {
			l = orig.Histogram.SizeProto()
			n += 1 + proto.Sov(uint64(l)) + l
		}
	case *Metric_ExponentialHistogram:
		if orig.ExponentialHistogram != nil {
			l = orig.ExponentialHistogram.SizeProto()
			n += 1 + proto.Sov(uint64(l)) + l
		}
	case *Metric_Summary:
		if orig.Summary != nil {
			l = orig.Summary.SizeProto()
			n += 1 + proto.Sov(uint64(l)) + l
		}
	}
	for i := range orig.Metadata {
		l = orig.Metadata[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	return n
}

func (orig *Metric) MarshalProto(buf []byte) int {
	pos := len(buf)
	var l int
	_ = l
	l = len(orig.Name)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.Name)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0xa
	}
	l = len(orig.Description)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.Description)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x12
	}
	l = len(orig.Unit)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.Unit)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x1a
	}
	switch orig := orig.Data.(type) {
	case *Metric_Gauge:
		if orig.Gauge != nil {
			l = orig.Gauge.MarshalProto(buf[:pos])
			pos -= l
			pos = proto.EncodeVarint(buf, pos, uint64(l))
			pos--
			buf[pos] = 0x2a
		}
	case *Metric_Sum:
		if orig.Sum != nil {
			l = orig.Sum.MarshalProto(buf[:pos])
			pos -= l
			pos = proto.EncodeVarint(buf, pos, uint64(l))
			pos--
			buf[pos] = 0x3a
		}
	case *Metric_Histogram:
		if orig.Histogram != nil {
			l = orig.Histogram.MarshalProto(buf[:pos])
			pos -= l
			pos = proto.EncodeVarint(buf, pos, uint64(l))
			pos--
			buf[pos] = 0x4a
		}
	case *Metric_ExponentialHistogram:
		if orig.ExponentialHistogram != nil {
			l = orig.ExponentialHistogram.MarshalProto(buf[:pos])
			pos -= l
			pos = proto.EncodeVarint(buf, pos, uint64(l))
			pos--
			buf[pos] = 0x52
		}
	case *Metric_Summary:
		if orig.Summary != nil {
			l = orig.Summary.MarshalProto(buf[:pos])
			pos -= l
			pos = proto.EncodeVarint(buf, pos, uint64(l))
			pos--
			buf[pos] = 0x5a
		}
	}
	for i := len(orig.Metadata) - 1; i >= 0; i-- {
		l = orig.Metadata[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x62
	}
	return len(buf) - pos
}

func (orig *Metric) UnmarshalProto(buf []byte) error {
	return orig.UnmarshalProtoState(buf, nil)
}

func (orig *Metric) UnmarshalProtoState(buf []byte, st *State) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		// If in a group parsing, move to the next tag.
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Name = BorrowString(st, buf, startPos, pos)

		case 2:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Description = BorrowString(st, buf, startPos, pos)

		case 3:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Unit", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Unit = BorrowString(st, buf, startPos, pos)

		case 5:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Gauge", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			ov := Alloc[Metric_Gauge](st)
			ov.Gauge = Alloc[Gauge](st)
			err = ov.Gauge.UnmarshalProtoState(buf[startPos:pos], st)
			if err != nil {
				return err
			}
			orig.Data = ov

		case 7:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Sum", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			ov := Alloc[Metric_Sum](st)
			ov.Sum = Alloc[Sum](st)
			err = ov.Sum.UnmarshalProtoState(buf[startPos:pos], st)
			if err != nil {
				return err
			}
			orig.Data = ov

		case 9:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Histogram", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			ov := Alloc[Metric_Histogram](st)
			ov.Histogram = Alloc[Histogram](st)
			err = ov.Histogram.UnmarshalProtoState(buf[startPos:pos], st)
			if err != nil {
				return err
			}
			orig.Data = ov

		case 10:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ExponentialHistogram", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			ov := Alloc[Metric_ExponentialHistogram](st)
			ov.ExponentialHistogram = Alloc[ExponentialHistogram](st)
			err = ov.ExponentialHistogram.UnmarshalProtoState(buf[startPos:pos], st)
			if err != nil {
				return err
			}
			orig.Data = ov

		case 11:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Summary", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			ov := Alloc[Metric_Summary](st)
			ov.Summary = Alloc[Summary](st)
			err = ov.Summary.UnmarshalProtoState(buf[startPos:pos], st)
			if err != nil {
				return err
			}
			orig.Data = ov

		case 12:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Metadata = AppendEstimated(st, orig.Metadata, KeyValue{}, len(buf)-pos, length+2)
			err = orig.Metadata[len(orig.Metadata)-1].UnmarshalProtoState(buf[startPos:pos], st)
			if err != nil {
				return err
			}
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestMetric() *Metric {
	orig := Alloc[Metric](nil)
	orig.Name = "test_name"
	orig.Description = "test_description"
	orig.Unit = "test_unit"
	orig.Data = &Metric_Gauge{Gauge: GenTestGauge()}
	orig.Metadata = []KeyValue{KeyValue{}, *GenTestKeyValue()}
	return orig
}

func GenTestMetricPtrSlice() []*Metric {
	orig := make([]*Metric, 5)
	orig[0] = Alloc[Metric](nil)
	orig[1] = GenTestMetric()
	orig[2] = Alloc[Metric](nil)
	orig[3] = GenTestMetric()
	orig[4] = Alloc[Metric](nil)
	return orig
}

func GenTestMetricSlice() []Metric {
	orig := make([]Metric, 5)
	orig[1] = *GenTestMetric()
	orig[3] = *GenTestMetric()
	return orig
}
