// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"encoding/binary"
	"fmt"
	"iter"
	"math"
	"sort"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpcollectorprofiles "go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/profiles/v1development"
	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlpprofiles "go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1development"
	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

func CopyOrigSampleSlice(dest, src []*otlpprofiles.Sample) []*otlpprofiles.Sample {
	var newDest []*otlpprofiles.Sample
	if cap(dest) < len(src) {
		newDest = make([]*otlpprofiles.Sample, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewOrigPtrSample()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewOrigPtrSample()
		}
	}
	for i := range src {
		CopyOrigSample(newDest[i], src[i])
	}
	return newDest
}

func GenerateOrigTestSampleSlice() []*otlpprofiles.Sample {
	orig := make([]*otlpprofiles.Sample, 5)
	orig[0] = NewOrigPtrSample()
	orig[1] = NewOrigPtrSample()
	FillOrigTestSample(orig[1])
	orig[2] = NewOrigPtrSample()
	orig[3] = NewOrigPtrSample()
	FillOrigTestSample(orig[3])
	orig[4] = NewOrigPtrSample()
	return orig
}

// UnmarshalJSONOrigSampleSlice unmarshals all properties from the current struct from the source iterator.
func UnmarshalJSONOrigSampleSlice(iter *json.Iterator) []*otlpprofiles.Sample {
	var orig []*otlpprofiles.Sample
	iter.ReadArrayCB(func(iter *json.Iterator) bool {
		orig = append(orig, NewOrigPtrSample())
		UnmarshalJSONOrigSample(orig[len(orig)-1], iter)
		return true
	})
	return orig
}
