// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gootlpmetrics "go.opentelemetry.io/proto/slim/otlp/metrics/v1"
	"google.golang.org/protobuf/proto"

	otlpcommon "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	otlpmetrics "go.opentelemetry.io/collector/pdata/internal/data/protogen/metrics/v1"
	"go.opentelemetry.io/collector/pdata/internal/json"

	"strconv"
)

func TestCopyOrigMetric(t *testing.T) {
	src := NewOrigPtrMetric()
	dest := NewOrigPtrMetric()
	CopyOrigMetric(dest, src)
	assert.Equal(t, NewOrigPtrMetric(), dest)
	*src = *GenTestOrigMetric()
	CopyOrigMetric(dest, src)
	assert.Equal(t, src, dest)
}

func TestMarshalAndUnmarshalJSONOrigMetricUnknown(t *testing.T) {
	iter := json.BorrowIterator([]byte(`{"unknown": "string"}`))
	defer json.ReturnIterator(iter)
	dest := NewOrigPtrMetric()
	UnmarshalJSONOrigMetric(dest, iter)
	require.NoError(t, iter.Error())
	assert.Equal(t, NewOrigPtrMetric(), dest)
}

func TestMarshalAndUnmarshalJSONOrigMetric(t *testing.T) {
	for i, src := range genTestValuesMetric() {
		t.Run("value_"+strconv.Itoa(i), func(t *testing.T) {
			stream := json.BorrowStream(nil)
			defer json.ReturnStream(stream)
			MarshalJSONOrigMetric(src, stream)
			require.NoError(t, stream.Error())

			iter := json.BorrowIterator(stream.Buffer())
			defer json.ReturnIterator(iter)
			dest := NewOrigPtrMetric()
			UnmarshalJSONOrigMetric(dest, iter)
			require.NoError(t, iter.Error())

			assert.Equal(t, src, dest)
		})
	}
}

func TestMarshalAndUnmarshalProtoOrigMetricUnknown(t *testing.T) {
	dest := NewOrigPtrMetric()
	// message Test { required int64 field = 1313; } encoding { "field": "1234" }
	require.NoError(t, UnmarshalProtoOrigMetric(dest, []byte{0x88, 0x52, 0xD2, 0x09}))
	assert.Equal(t, NewOrigPtrMetric(), dest)
}

func TestMarshalAndUnmarshalProtoOrigMetric(t *testing.T) {
	for i, src := range genTestValuesMetric() {
		t.Run("value_"+strconv.Itoa(i), func(t *testing.T) {
			buf := make([]byte, SizeProtoOrigMetric(src))
			gotSize := MarshalProtoOrigMetric(src, buf)
			assert.Equal(t, len(buf), gotSize)

			dest := NewOrigPtrMetric()
			require.NoError(t, UnmarshalProtoOrigMetric(dest, buf))
			assert.Equal(t, src, dest)
		})
	}
}

func TestMarshalAndUnmarshalProtoViaProtobufMetric(t *testing.T) {
	for i, src := range genTestValuesMetric() {
		t.Run("value_"+strconv.Itoa(i), func(t *testing.T) {
			buf := make([]byte, SizeProtoOrigMetric(src))
			gotSize := MarshalProtoOrigMetric(src, buf)
			assert.Equal(t, len(buf), gotSize)

			goDest := &gootlpmetrics.Metric{}
			require.NoError(t, proto.Unmarshal(buf, goDest))

			goBuf, err := proto.Marshal(goDest)
			require.NoError(t, err)

			dest := NewOrigPtrMetric()
			require.NoError(t, UnmarshalProtoOrigMetric(dest, goBuf))
			assert.Equal(t, src, dest)
		})
	}
}

func genTestValuesMetric() []*otlpmetrics.Metric {
	return []*otlpmetrics.Metric{
		NewOrigPtrMetric(),

		{Name: "test_name"},
		{Description: "test_description"},
		{Unit: "test_unit"},
		{Data: &otlpmetrics.Metric_Gauge{Gauge: GenTestOrigGauge()}},
		{Data: &otlpmetrics.Metric_Gauge{Gauge: &otlpmetrics.Gauge{}}},
		{Data: &otlpmetrics.Metric_Sum{Sum: GenTestOrigSum()}},
		{Data: &otlpmetrics.Metric_Sum{Sum: &otlpmetrics.Sum{}}},
		{Data: &otlpmetrics.Metric_Histogram{Histogram: GenTestOrigHistogram()}},
		{Data: &otlpmetrics.Metric_Histogram{Histogram: &otlpmetrics.Histogram{}}},
		{Data: &otlpmetrics.Metric_ExponentialHistogram{ExponentialHistogram: GenTestOrigExponentialHistogram()}},
		{Data: &otlpmetrics.Metric_ExponentialHistogram{ExponentialHistogram: &otlpmetrics.ExponentialHistogram{}}},
		{Data: &otlpmetrics.Metric_Summary{Summary: GenTestOrigSummary()}},
		{Data: &otlpmetrics.Metric_Summary{Summary: &otlpmetrics.Summary{}}},
		{Metadata: []otlpcommon.KeyValue{{}, *GenTestOrigKeyValue()}},
	}
}
