// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"testing"

	"github.com/stretchr/testify/assert"

	otlpmetrics "go.opentelemetry.io/collector/pdata/internal/data/protogen/metrics/v1"
)

func TestCopyOrigSum(t *testing.T) {
	src := &otlpmetrics.Sum{}
	dest := &otlpmetrics.Sum{}
	CopyOrigSum(dest, src)
	assert.Equal(t, &otlpmetrics.Sum{}, dest)
	FillOrigTestSum(src)
	CopyOrigSum(dest, src)
	assert.Equal(t, src, dest)
}
