// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	otlptrace "go.opentelemetry.io/collector/pdata/internal/data/protogen/trace/v1"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

func CopyOrigResourceSpansSlice(dest, src []*otlptrace.ResourceSpans) []*otlptrace.ResourceSpans {
	var newDest []*otlptrace.ResourceSpans
	if cap(dest) < len(src) {
		newDest = make([]*otlptrace.ResourceSpans, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewOrigPtrResourceSpans()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewOrigPtrResourceSpans()
		}
	}
	for i := range src {
		CopyOrigResourceSpans(newDest[i], src[i])
	}
	return newDest
}

func GenerateOrigTestResourceSpansSlice() []*otlptrace.ResourceSpans {
	orig := make([]*otlptrace.ResourceSpans, 5)
	orig[0] = NewOrigPtrResourceSpans()
	orig[1] = NewOrigPtrResourceSpans()
	FillOrigTestResourceSpans(orig[1])
	orig[2] = NewOrigPtrResourceSpans()
	orig[3] = NewOrigPtrResourceSpans()
	FillOrigTestResourceSpans(orig[3])
	orig[4] = NewOrigPtrResourceSpans()
	return orig
}

// UnmarshalJSONOrigResourceSpansSlice unmarshals all properties from the current struct from the source iterator.
func UnmarshalJSONOrigResourceSpansSlice(iter *json.Iterator) []*otlptrace.ResourceSpans {
	var orig []*otlptrace.ResourceSpans
	iter.ReadArrayCB(func(iter *json.Iterator) bool {
		orig = append(orig, NewOrigPtrResourceSpans())
		UnmarshalJSONOrigResourceSpans(orig[len(orig)-1], iter)
		return true
	})
	return orig
}
