// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"sync"

	"go.opentelemetry.io/collector/pdata"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

// ProfilesData represents the profiles data that can be stored in persistent storage,
// OR can be embedded by other protocols that transfer OTLP profiles data but do not
// implement the OTLP protocol.
type LazyProfilesData struct {
	ProfilesData
	bytes []byte
}

var (
	protoPoolLazyProfilesData = sync.Pool{
		New: func() any {
			return &LazyProfilesData{}
		},
	}
)

func NewLazyProfilesData() *LazyProfilesData {
	if !UseProtoPooling.IsEnabled() {
		return &LazyProfilesData{}
	}
	return protoPoolLazyProfilesData.Get().(*LazyProfilesData)
}

func DeleteLazyProfilesData(orig *LazyProfilesData, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	DeleteProfilesData(&orig.ProfilesData, false)

	orig.Reset()
	if nullable {
		protoPoolLazyProfilesData.Put(orig)
	}
}

func CopyLazyProfilesData(dest, src *LazyProfilesData) *LazyProfilesData {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewLazyProfilesData()
	}

	CopyProfilesData(&dest.ProfilesData, &src.ProfilesData)
	dest.bytes = src.bytes

	return dest
}

func CopyLazyProfilesDataSlice(dest, src []LazyProfilesData) []LazyProfilesData {
	var newDest []LazyProfilesData
	if cap(dest) < len(src) {
		newDest = make([]LazyProfilesData, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteLazyProfilesData(&dest[i], false)
		}
	}
	for i := range src {
		CopyLazyProfilesData(&newDest[i], &src[i])
	}
	return newDest
}

func CopyLazyProfilesDataPtrSlice(dest, src []*LazyProfilesData) []*LazyProfilesData {
	var newDest []*LazyProfilesData
	if cap(dest) < len(src) {
		newDest = make([]*LazyProfilesData, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewLazyProfilesData()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteLazyProfilesData(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewLazyProfilesData()
		}
	}
	for i := range src {
		CopyLazyProfilesData(newDest[i], src[i])
	}
	return newDest
}

func (orig *LazyProfilesData) Reset() {
	*orig = LazyProfilesData{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *LazyProfilesData) MarshalJSON(dest *json.Stream) {
	orig.ProfilesData.MarshalJSON(dest)
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *LazyProfilesData) UnmarshalJSON(iter *json.Iterator) {
	orig.ProfilesData.UnmarshalJSON(iter)
}

func (orig *LazyProfilesData) SizeProto() int {
	return orig.ProfilesData.SizeProto()
}

func (orig *LazyProfilesData) MarshalProto(buf []byte) int {
	return orig.ProfilesData.MarshalProto(buf)
}

func (orig *LazyProfilesData) UnmarshalProto(buf []byte) error {
	return orig.UnmarshalProtoOpts(buf, &pdata.DefaultUnmarshalOptions)
}

func (orig *LazyProfilesData) UnmarshalProtoOpts(buf []byte, opts *pdata.UnmarshalOptions) error {
	if !opts.LazyDecoding {
		return orig.ProfilesData.UnmarshalProtoOpts(buf, opts)
	}
	if err := SkipProfilesDataProto(buf); err != nil {
		return err
	}
	orig.bytes = buf
	orig.ProfilesData.Reset()
	return nil
}

func SkipLazyProfilesDataProto(buf []byte) error {
	return SkipProfilesDataProto(buf)
}

func (orig *LazyProfilesData) FinishUnmarshal(buf *ProfilesData) (*ProfilesData, error) {
	if len(orig.bytes) == 0 {
		return &orig.ProfilesData, nil
	}
	err := buf.UnmarshalProto(orig.bytes)
	return buf, err
}

func GenTestLazyProfilesData() *LazyProfilesData {
	orig := NewLazyProfilesData()
	orig.ProfilesData = *GenTestProfilesData()
	return orig
}

func GenTestLazyProfilesDataPtrSlice() []*LazyProfilesData {
	orig := make([]*LazyProfilesData, 5)
	orig[0] = NewLazyProfilesData()
	orig[1] = GenTestLazyProfilesData()
	orig[2] = NewLazyProfilesData()
	orig[3] = GenTestLazyProfilesData()
	orig[4] = NewLazyProfilesData()
	return orig
}

func GenTestLazyProfilesDataSlice() []LazyProfilesData {
	orig := make([]LazyProfilesData, 5)
	orig[1] = *GenTestLazyProfilesData()
	orig[3] = *GenTestLazyProfilesData()
	return orig
}
