// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"sync"

	"go.opentelemetry.io/collector/pdata"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

// ScopeSpans is a collection of spans from a LibraryInstrumentation.
type LazyScopeSpans struct {
	ScopeSpans
	bytes []byte
}

var (
	protoPoolLazyScopeSpans = sync.Pool{
		New: func() any {
			return &LazyScopeSpans{}
		},
	}
)

func NewLazyScopeSpans() *LazyScopeSpans {
	if !UseProtoPooling.IsEnabled() {
		return &LazyScopeSpans{}
	}
	return protoPoolLazyScopeSpans.Get().(*LazyScopeSpans)
}

func DeleteLazyScopeSpans(orig *LazyScopeSpans, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	DeleteScopeSpans(&orig.ScopeSpans, false)

	orig.Reset()
	if nullable {
		protoPoolLazyScopeSpans.Put(orig)
	}
}

func CopyLazyScopeSpans(dest, src *LazyScopeSpans) *LazyScopeSpans {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewLazyScopeSpans()
	}

	CopyScopeSpans(&dest.ScopeSpans, &src.ScopeSpans)
	dest.bytes = src.bytes

	return dest
}

func CopyLazyScopeSpansSlice(dest, src []LazyScopeSpans) []LazyScopeSpans {
	var newDest []LazyScopeSpans
	if cap(dest) < len(src) {
		newDest = make([]LazyScopeSpans, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteLazyScopeSpans(&dest[i], false)
		}
	}
	for i := range src {
		CopyLazyScopeSpans(&newDest[i], &src[i])
	}
	return newDest
}

func CopyLazyScopeSpansPtrSlice(dest, src []*LazyScopeSpans) []*LazyScopeSpans {
	var newDest []*LazyScopeSpans
	if cap(dest) < len(src) {
		newDest = make([]*LazyScopeSpans, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewLazyScopeSpans()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteLazyScopeSpans(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewLazyScopeSpans()
		}
	}
	for i := range src {
		CopyLazyScopeSpans(newDest[i], src[i])
	}
	return newDest
}

func (orig *LazyScopeSpans) Reset() {
	*orig = LazyScopeSpans{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *LazyScopeSpans) MarshalJSON(dest *json.Stream) {
	orig.ScopeSpans.MarshalJSON(dest)
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *LazyScopeSpans) UnmarshalJSON(iter *json.Iterator) {
	orig.ScopeSpans.UnmarshalJSON(iter)
}

func (orig *LazyScopeSpans) SizeProto() int {
	return orig.ScopeSpans.SizeProto()
}

func (orig *LazyScopeSpans) MarshalProto(buf []byte) int {
	return orig.ScopeSpans.MarshalProto(buf)
}

func (orig *LazyScopeSpans) UnmarshalProto(buf []byte) error {
	return orig.UnmarshalProtoOpts(buf, &pdata.DefaultUnmarshalOptions)
}

func (orig *LazyScopeSpans) UnmarshalProtoOpts(buf []byte, opts *pdata.UnmarshalOptions) error {
	if !opts.LazyDecoding {
		return orig.ScopeSpans.UnmarshalProtoOpts(buf, opts)
	}
	orig.bytes = buf
	orig.ScopeSpans.Reset()
	return nil
}

func (orig *LazyScopeSpans) FinishUnmarshal(buf *ScopeSpans) (*ScopeSpans, error) {
	if len(orig.bytes) == 0 {
		return &orig.ScopeSpans, nil
	}
	err := buf.UnmarshalProto(orig.bytes)
	return buf, err
}

func GenTestLazyScopeSpans() *LazyScopeSpans {
	orig := NewLazyScopeSpans()
	orig.ScopeSpans = *GenTestScopeSpans()
	return orig
}

func GenTestLazyScopeSpansPtrSlice() []*LazyScopeSpans {
	orig := make([]*LazyScopeSpans, 5)
	orig[0] = NewLazyScopeSpans()
	orig[1] = GenTestLazyScopeSpans()
	orig[2] = NewLazyScopeSpans()
	orig[3] = GenTestLazyScopeSpans()
	orig[4] = NewLazyScopeSpans()
	return orig
}

func GenTestLazyScopeSpansSlice() []LazyScopeSpans {
	orig := make([]LazyScopeSpans, 5)
	orig[1] = *GenTestLazyScopeSpans()
	orig[3] = *GenTestLazyScopeSpans()
	return orig
}
