// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package plog

import (
	"testing"
	"unsafe"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gootlpcollectorlogs "go.opentelemetry.io/proto/slim/otlp/collector/logs/v1"
	gootlplogs "go.opentelemetry.io/proto/slim/otlp/logs/v1"
	"google.golang.org/protobuf/proto"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpcollectorlogs "go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/logs/v1"
	otlplogs "go.opentelemetry.io/collector/pdata/internal/data/protogen/logs/v1"
	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestLogs_MoveTo(t *testing.T) {
	ms := generateTestLogs()
	dest := NewLogs()
	ms.MoveTo(dest)
	assert.Equal(t, NewLogs(), ms)
	assert.Equal(t, generateTestLogs(), dest)
	dest.MoveTo(dest)
	assert.Equal(t, generateTestLogs(), dest)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newLogs(internal.NewOrigPtrExportLogsServiceRequest(), sharedState)) })
	assert.Panics(t, func() { newLogs(internal.NewOrigPtrExportLogsServiceRequest(), sharedState).MoveTo(dest) })
}

func TestLogs_CopyTo(t *testing.T) {
	ms := NewLogs()
	orig := NewLogs()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	orig = generateTestLogs()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newLogs(internal.NewOrigPtrExportLogsServiceRequest(), sharedState)) })
}

func TestLogs_ResourceLogs(t *testing.T) {
	ms := NewLogs()
	assert.Equal(t, NewResourceLogsSlice(), ms.ResourceLogs())
	ms.getOrig().ResourceLogs = internal.GenerateOrigTestResourceLogsSlice()
	assert.Equal(t, generateTestResourceLogsSlice(), ms.ResourceLogs())
}

func generateTestLogs() Logs {
	return Logs(internal.GenerateTestLogs())
}
