codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: master  # only use the latest copy on master branch

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        enabled: yes
        target: 85%  # This needs to be updated to 90 or 95.
    patch:
      default:
        enabled: yes
        target: 95%
