// Code generated by mdatagen. DO NOT EDIT.

package queuebatch

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestBatchConfigValidate_DefaultValid(t *testing.T) {
	cfg := NewDefaultBatchConfig()

	require.NoError(t, cfg.Validate())
}

func TestBatchConfigValidate_ExclusiveMinimumFlushTimeout(t *testing.T) {
	cfg := NewDefaultBatchConfig()
	cfg.FlushTimeout = 0

	require.ErrorContains(t, cfg.Validate(), "flush_timeout value must be greater than 0")
}

func TestBatchConfigValidate_MinimumMaxSize(t *testing.T) {
	cfg := NewDefaultBatchConfig()
	cfg.MaxSize = 0 - 1

	require.ErrorContains(t, cfg.Validate(), "max_size value must be greater than or equal to 0")
}

func TestBatchConfigValidate_MinimumMinSize(t *testing.T) {
	cfg := NewDefaultBatchConfig()
	cfg.MinSize = 0 - 1

	require.ErrorContains(t, cfg.Validate(), "min_size value must be greater than or equal to 0")
}

func TestConfigValidate_ExclusiveMinimumNumConsumers(t *testing.T) {
	cfg := Config{}
	cfg.NumConsumers = 0

	require.ErrorContains(t, cfg.Validate(), "num_consumers value must be greater than 0")
}

func TestConfigValidate_ExclusiveMinimumQueueSize(t *testing.T) {
	cfg := Config{}
	cfg.QueueSize = 0

	require.ErrorContains(t, cfg.Validate(), "queue_size value must be greater than 0")
}

func TestPartitionConfigValidate_DefaultValid(t *testing.T) {
	cfg := NewDefaultPartitionConfig()

	require.NoError(t, cfg.Validate())
}

func TestPartitionConfigValidate_ExclusiveMinimumCacheSize(t *testing.T) {
	cfg := NewDefaultPartitionConfig()
	cfg.CacheSize = 0

	require.ErrorContains(t, cfg.Validate(), "cache_size value must be greater than 0")
}

func TestPartitionConfigValidate_ExclusiveMinimumIdleTimeout(t *testing.T) {
	cfg := NewDefaultPartitionConfig()
	cfg.IdleTimeout = 0

	require.ErrorContains(t, cfg.Validate(), "idle_timeout value must be greater than 0")
}
