// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: persistent_queue.proto

package queuebatch

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueueMetadata holds all persistent metadata for the queue.
type QueueMetadata struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SizerType                []byte                 `protobuf:"bytes,1,opt,name=sizer_type,json=sizerType,proto3" json:"sizer_type,omitempty"`
	ReadIndex                uint64                 `protobuf:"varint,2,opt,name=read_index,json=readIndex,proto3" json:"read_index,omitempty"`
	WriteIndex               uint64                 `protobuf:"varint,3,opt,name=write_index,json=writeIndex,proto3" json:"write_index,omitempty"`
	QueueSize                int64                  `protobuf:"varint,4,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`
	CurrentlyDispatchedItems []uint64               `protobuf:"varint,5,rep,packed,name=currently_dispatched_items,json=currentlyDispatchedItems,proto3" json:"currently_dispatched_items,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *QueueMetadata) Reset() {
	*x = QueueMetadata{}
	mi := &file_persistent_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMetadata) ProtoMessage() {}

func (x *QueueMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_persistent_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMetadata.ProtoReflect.Descriptor instead.
func (*QueueMetadata) Descriptor() ([]byte, []int) {
	return file_persistent_queue_proto_rawDescGZIP(), []int{0}
}

func (x *QueueMetadata) GetSizerType() []byte {
	if x != nil {
		return x.SizerType
	}
	return nil
}

func (x *QueueMetadata) GetReadIndex() uint64 {
	if x != nil {
		return x.ReadIndex
	}
	return 0
}

func (x *QueueMetadata) GetWriteIndex() uint64 {
	if x != nil {
		return x.WriteIndex
	}
	return 0
}

func (x *QueueMetadata) GetQueueSize() int64 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

func (x *QueueMetadata) GetCurrentlyDispatchedItems() []uint64 {
	if x != nil {
		return x.CurrentlyDispatchedItems
	}
	return nil
}

var File_persistent_queue_proto protoreflect.FileDescriptor

const file_persistent_queue_proto_rawDesc = "" +
	"\n" +
	"\x16persistent_queue.proto\x12Copentelemetry.collector.exporter.exporterhelper.internal.queuebatch\"\xcb\x01\n" +
	"\rQueueMetadata\x12\x1d\n" +
	"\n" +
	"sizer_type\x18\x01 \x01(\fR\tsizerType\x12\x1d\n" +
	"\n" +
	"read_index\x18\x02 \x01(\x04R\treadIndex\x12\x1f\n" +
	"\vwrite_index\x18\x03 \x01(\x04R\n" +
	"writeIndex\x12\x1d\n" +
	"\n" +
	"queue_size\x18\x04 \x01(\x03R\tqueueSize\x12<\n" +
	"\x1acurrently_dispatched_items\x18\x05 \x03(\x04R\x18currentlyDispatchedItemsBKZIgo.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatchb\x06proto3"

var (
	file_persistent_queue_proto_rawDescOnce sync.Once
	file_persistent_queue_proto_rawDescData []byte
)

func file_persistent_queue_proto_rawDescGZIP() []byte {
	file_persistent_queue_proto_rawDescOnce.Do(func() {
		file_persistent_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_persistent_queue_proto_rawDesc), len(file_persistent_queue_proto_rawDesc)))
	})
	return file_persistent_queue_proto_rawDescData
}

var file_persistent_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_persistent_queue_proto_goTypes = []any{
	(*QueueMetadata)(nil), // 0: opentelemetry.collector.exporter.exporterhelper.internal.queuebatch.QueueMetadata
}
var file_persistent_queue_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_persistent_queue_proto_init() }
func file_persistent_queue_proto_init() {
	if File_persistent_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_persistent_queue_proto_rawDesc), len(file_persistent_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_persistent_queue_proto_goTypes,
		DependencyIndexes: file_persistent_queue_proto_depIdxs,
		MessageInfos:      file_persistent_queue_proto_msgTypes,
	}.Build()
	File_persistent_queue_proto = out.File
	file_persistent_queue_proto_goTypes = nil
	file_persistent_queue_proto_depIdxs = nil
}
