// Copyright 2020 OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package internal

// Defined here just to be available as returned message for the fields.
// This will not be generated by this class.
var stringMap = &sliceStruct{
	structName: "StringMap",
	element:    stringKeyValue,
}

var stringKeyValue = &messageStruct{}

// Defined here just to be available as returned message for the fields.
// This will not be generated by this class.
var attributeMap = &sliceStruct{
	structName: "AttributeMap",
	element:    attributeKeyValue,
}

var attributeKeyValue = &messageStruct{}
