// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test_pkg

import configcompression "go.opentelemetry.io/collector/cmd/mdatagen/internal/testdata/config_gen/struct_from_ref/configcompression"

type Config struct {
	// ExampleType corresponds to the JSON schema field "ExampleType".
	ExampleType *ConfigExampleType `mapstructure:"ExampleType"`
}

type ConfigExampleType struct {
	// Compression corresponds to the JSON schema field "compression".
	Compression *configcompression.Type `mapstructure:"compression"`
}
