.PHONY: generate
generate:
	go tool go.opentelemetry.io/collector/cmd/builder --verbose --config manifest.yaml
	cd build/collector && go mod tidy

.PHONY: tidy
tidy:
	@if [ -d build/collector ]; then \
		cd build/collector && go mod tidy; \
	else \
		go mod tidy; \
	fi

.PHONY: run
run: generate
	@cd build/collector && \
	./{{.Name}} --config ../../config.yaml
