$defs:
  http_config:
    type: object
    properties:
      logs_url_path:
        description: The URL path to receive logs on. If omitted "/v1/logs" will be used.
        $ref: sanitized_url_path
      metrics_url_path:
        description: The URL path to receive metrics on. If omitted "/v1/metrics" will be used.
        $ref: sanitized_url_path
      traces_url_path:
        description: The URL path to receive traces on. If omitted "/v1/traces" will be used.
        $ref: sanitized_url_path
    allOf:
      - $ref: /config/confighttp.server_config
  protocols:
    description: Protocols is the configuration for the supported protocols. At least one of `grpc` or `http` must be set.
    type: object
    properties:
      grpc:
        description: Configuration for the OTLP gRPC server. Enable by setting this section (or its `endpoint`).
        x-optional: true
        $ref: /config/configgrpc.server_config
      http:
        description: Configuration for the OTLP HTTP server. Enable by setting this section (or its `endpoint`).
        x-optional: true
        $ref: http_config
  sanitized_url_path:
    description: A URL path. A leading slash is automatically prepended when missing.
    type: string
description: Config defines configuration for OTLP receiver.
type: object
properties:
  protocols:
    description: Protocols is the configuration for the supported protocols, currently gRPC and HTTP (Proto and JSON).
    $ref: protocols
