// Code generated by mdatagen. DO NOT EDIT.

package samplepkg

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestSampleConfigValidate_DefaultValid(t *testing.T) {
	cfg := NewDefaultSampleConfig()

	require.NoError(t, cfg.Validate())
}

func TestConfigValidate_RequiredHostName(t *testing.T) {
	cfg := NewDefaultSampleConfig()
	cfg.HostName = ""

	require.ErrorContains(t, cfg.Validate(), "host_name is required")
}

func TestConfigValidate_RequiredPort(t *testing.T) {
	cfg := NewDefaultSampleConfig()
	cfg.Port = ""

	require.ErrorContains(t, cfg.Validate(), "port is required")
}
