// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"go.opentelemetry.io/collector/receiver/receiverhelper/internal/metadata"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := SetupTelemetry()
	tb, err := metadata.NewTelemetryBuilder(
		testTel.NewTelemetrySettings(),
	)
	require.NoError(t, err)
	require.NotNil(t, tb)
	tb.ReceiverAcceptedLogRecords.Add(context.Background(), 1)
	tb.ReceiverAcceptedMetricPoints.Add(context.Background(), 1)
	tb.ReceiverAcceptedSpans.Add(context.Background(), 1)
	tb.ReceiverRefusedLogRecords.Add(context.Background(), 1)
	tb.ReceiverRefusedMetricPoints.Add(context.Background(), 1)
	tb.ReceiverRefusedSpans.Add(context.Background(), 1)

	testTel.AssertMetrics(t, []metricdata.Metrics{
		{
			Name:        "otelcol_receiver_accepted_log_records",
			Description: "Number of log records successfully pushed into the pipeline. [alpha]",
			Unit:        "{records}",
			Data: metricdata.Sum[int64]{
				Temporality: metricdata.CumulativeTemporality,
				IsMonotonic: true,
				DataPoints: []metricdata.DataPoint[int64]{
					{},
				},
			},
		},
		{
			Name:        "otelcol_receiver_accepted_metric_points",
			Description: "Number of metric points successfully pushed into the pipeline. [alpha]",
			Unit:        "{datapoints}",
			Data: metricdata.Sum[int64]{
				Temporality: metricdata.CumulativeTemporality,
				IsMonotonic: true,
				DataPoints: []metricdata.DataPoint[int64]{
					{},
				},
			},
		},
		{
			Name:        "otelcol_receiver_accepted_spans",
			Description: "Number of spans successfully pushed into the pipeline. [alpha]",
			Unit:        "{spans}",
			Data: metricdata.Sum[int64]{
				Temporality: metricdata.CumulativeTemporality,
				IsMonotonic: true,
				DataPoints: []metricdata.DataPoint[int64]{
					{},
				},
			},
		},
		{
			Name:        "otelcol_receiver_refused_log_records",
			Description: "Number of log records that could not be pushed into the pipeline. [alpha]",
			Unit:        "{records}",
			Data: metricdata.Sum[int64]{
				Temporality: metricdata.CumulativeTemporality,
				IsMonotonic: true,
				DataPoints: []metricdata.DataPoint[int64]{
					{},
				},
			},
		},
		{
			Name:        "otelcol_receiver_refused_metric_points",
			Description: "Number of metric points that could not be pushed into the pipeline. [alpha]",
			Unit:        "{datapoints}",
			Data: metricdata.Sum[int64]{
				Temporality: metricdata.CumulativeTemporality,
				IsMonotonic: true,
				DataPoints: []metricdata.DataPoint[int64]{
					{},
				},
			},
		},
		{
			Name:        "otelcol_receiver_refused_spans",
			Description: "Number of spans that could not be pushed into the pipeline. [alpha]",
			Unit:        "{spans}",
			Data: metricdata.Sum[int64]{
				Temporality: metricdata.CumulativeTemporality,
				IsMonotonic: true,
				DataPoints: []metricdata.DataPoint[int64]{
					{},
				},
			},
		},
	}, metricdatatest.IgnoreTimestamp(), metricdatatest.IgnoreValue())

	AssertEqualReceiverAcceptedLogRecords(t, testTel.Telemetry,
		[]metricdata.DataPoint[int64]{{}},
		metricdatatest.IgnoreTimestamp(), metricdatatest.IgnoreValue())

	AssertEqualReceiverAcceptedMetricPoints(t, testTel.Telemetry,
		[]metricdata.DataPoint[int64]{{}},
		metricdatatest.IgnoreTimestamp(), metricdatatest.IgnoreValue())

	AssertEqualReceiverAcceptedSpans(t, testTel.Telemetry,
		[]metricdata.DataPoint[int64]{{}},
		metricdatatest.IgnoreTimestamp(), metricdatatest.IgnoreValue())

	AssertEqualReceiverRefusedLogRecords(t, testTel.Telemetry,
		[]metricdata.DataPoint[int64]{{}},
		metricdatatest.IgnoreTimestamp(), metricdatatest.IgnoreValue())

	AssertEqualReceiverRefusedMetricPoints(t, testTel.Telemetry,
		[]metricdata.DataPoint[int64]{{}},
		metricdatatest.IgnoreTimestamp(), metricdatatest.IgnoreValue())

	AssertEqualReceiverRefusedSpans(t, testTel.Telemetry,
		[]metricdata.DataPoint[int64]{{}},
		metricdatatest.IgnoreTimestamp(), metricdatatest.IgnoreValue())

	require.NoError(t, testTel.Shutdown(context.Background()))
}
