receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:HTTP_HOST:-localhost:4317}

processors:
  batch:

exporters:
  debug:

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - debug
