config:
  "$id": "https://opentelemetry.io/collector/configtls",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$defs":
    "config":
      "type": "object"
      "additionalProperties": false
      "properties":
        ca_file:
          type: string
        ca_pem:
          type: string
        include_system_ca_certs_pool:
          type: boolean
        cert_file:
          type: string
        cert_pem:
          type: string
        key_file:
          type: string
        key_pem:
          type: string
        min_version:
          type: string
        max_version:
          type: string
        cipher_suites:
          type: array
          items:
            type: string
        reload_interval:
          "type": "string",
          "format": "duration"
        curve_preferences:
          type: array
          items:
            type: string
        tpm:
          type: object
          properties:
            enabled:
              type: boolean
            path:
              type: string
            owner_auth:
              type: string
            auth:
              type: string
    "clientConfig":
      type: "object"
      allOf:
        $ref: "https://opentelemetry.io/collector/configtls#$defs/config"
      properties:
        insecure:
          type: boolean
        insecure_skip_verify:
          type: boolean
        server_name_override:
          type: string
    "serverConfig":
      type: "object"
      allOf:
        $ref: "https://opentelemetry.io/collector/configtls#$defs/config"
      properties:
        client_ca_file:
          type: string
        client_ca_file_reload:
          type: boolean
