type: config/configtls
parent: config
github_project: open-telemetry/opentelemetry-collector

status:
  disable_codecov_badge: true
  class: pkg

exported_configs:
  client_config:
    description: Contains TLS configurations that are specific to client connections in addition to the common configurations. This should be used by components configuring TLS client connections.
    properties:
      insecure:
        description: In gRPC and HTTP when set to true, this is used to disable the client transport security. See https://godoc.org/google.golang.org/grpc#WithInsecure for gRPC. Please refer to https://godoc.org/crypto/tls#Config for more information. (optional, default false)
        type: bool
      insecure_skip_verify:
        description: Enables TLS but not verify the certificate.
        type: bool
      server_name_override:
        description: Server name requested by client for virtual hosting. This sets the ServerName in the TLSConfig. Please refer to https://godoc.org/crypto/tls#Config for more information. (optional)
        type: string
        go_struct:
          field_name: ServerName
      config:
        $ref: config
        embed: true
        go_struct:
          anonymous: true
  config:
    description: 'Exposes the common client and server TLS configurations. Note: Since there isn''t anything specific to a server connection. Components with server connections should use Config.'
    properties:
      ca_file:
        description: Path to the CA cert. For a client this verifies the server certificate. For a server this verifies client certificates. If empty uses system root CA. (optional)
        type: string
      ca_pem:
        description: In memory PEM encoded cert. (optional)
        type: opaque_string
      cert_file:
        description: Path to the TLS cert to use for TLS required connections. (optional)
        type: string
      cert_pem:
        description: In memory PEM encoded TLS cert to use for TLS required connections. (optional)
        type: opaque_string
      cipher_suites:
        description: A list of TLS cipher suites that the TLS transport can use. If left blank, a safe default list is used. See https://go.dev/src/crypto/tls/cipher_suites.go for a list of supported cipher suites.
        type: slice
        values:
          type: string
      include_insecure_cipher_suites:
        description: Enables support for insecure cipher suites. When set to true, cipher suites returned by tls.InsecureCipherSuites() will be available for selection in addition to the secure ones. This should only be used when working with legacy systems that require insecure cipher suites. (optional, default false)
        type: bool
      curve_preferences:
        description: Contains the elliptic curves that will be used in an ECDHE handshake, in preference order Defaults to empty list and "crypto/tls" defaults are used, internally.
        type: slice
        values:
          type: string
      include_system_ca_certs_pool:
        description: If true, load system CA certificates pool in addition to the certificates configured in this struct.
        type: bool
      key_file:
        description: Path to the TLS key to use for TLS required connections. (optional)
        type: string
      key_pem:
        description: In memory PEM encoded TLS key to use for TLS required connections. (optional)
        type: opaque_string
      max_version:
        description: Sets the maximum TLS version that is acceptable. If not set, refer to crypto/tls for defaults. (optional)
        type: string
      min_version:
        description: Sets the minimum TLS version that is acceptable. If not set, TLS 1.2 will be used. (optional)
        type: string
      reload_interval:
        description: Specifies the duration after which the certificate will be reloaded If not set, it will never be reloaded (optional)
        type: duration
      tpm:
        description: Trusted platform module configuration
        $ref: tpm_config
        go_struct:
          field_name: TPMConfig
    default: {}
  server_config:
    description: Contains TLS configurations that are specific to server connections in addition to the common configurations. This should be used by components configuring TLS server connections.
    properties:
      client_ca_file:
        description: Path to the TLS cert to use by the server to verify a client certificate. (optional) This sets the ClientCAs and ClientAuth to RequireAndVerifyClientCert in the TLSConfig. Please refer to https://godoc.org/crypto/tls#Config for more information. (optional)
        type: string
      client_ca_file_reload:
        description: Reload the ClientCAs file when it is modified (optional, default false)
        type: bool
        go_struct:
          field_name: ReloadClientCAFile
      config:
        $ref: config
        embed: true
        go_struct:
          anonymous: true
  tpm_config:
    description: Defines trusted platform module configuration for storing TLS keys.
    properties:
      auth:
        type: string
      enabled:
        type: bool
      owner_auth:
        type: string
      path:
        description: The path to the TPM device or Unix domain socket. For instance /dev/tpm0 or /dev/tpmrm0.
        type: string

tests:
  goleak:
    ignore:
      top:
        # https://github.com/open-telemetry/opentelemetry-collector/issues/9221
        - "go.opentelemetry.io/collector/config/configtls.(*clientCAsFileReloader).handleWatcherEvents"
      any:
        # https://github.com/open-telemetry/opentelemetry-collector/issues/9221
        - "github.com/fsnotify/fsnotify.(*inotify).readEvents"
        - "github.com/fsnotify/fsnotify.(*readDirChangesW).readEvents"
