$defs:
  expvar_config:
    description: ExpvarConfig has the configuration for the expvar service.
    type: object
    properties:
      enabled:
        description: Enabled indicates whether to enable expvar service. (default = false)
        type: boolean
description: Config has the configuration for the extension enabling the zPages extension.
type: object
properties:
  expvar:
    $ref: expvar_config
allOf:
  - $ref: /config/confighttp.server_config
