change_type: bug_fix

component: confighttp

note: "confighttp.ToServer now sets ErrorLog with a default logger backed by Zap"

issues: [11820]

subtext: |

  This change ensures that the http.Server's ErrorLog is correctly set using Zap's logger at the error level, addressing the issue of error logs being printed using a different logger.

change_logs: []
