name: 'Add code owners to a PR'
on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  add-owners-to-pr:
    runs-on: ubuntu-24.04
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' && github.repository_owner == 'open-telemetry' }}
    steps:
      - uses: actions/checkout@v4

      - name: Run add-codeowners-to-pr.sh
        run: ./.github/workflows/scripts/add-codeowners-to-pr.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR: ${{ github.event.number }}
