name: changelog

on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened, labeled, unlabeled, edited]
    branches:
      - main
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  changelog:
    permissions:
      contents: read
      pull-requests: read
    uses: open-telemetry/shared-workflows/.github/workflows/chloggen.yml@0cc57aeabf2a31cf41114e7b24561f21a04e360b # v0.18.0
