name: Changelog

on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened, labeled, unlabeled, edited]
    branches:
      - main
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  changelog:
    if: ${{ github.event_name == 'pull_request' }}
    uses:  open-telemetry/opentelemetry-collector-contrib/.github/workflows/changelog.yml@67f7d3fa89cd5142b16a11a0c2b370f91690f820
