name: Spell Check

on: [push, pull_request]

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run cSpell
        uses: streetsidesoftware/cspell-action@157048954070986ce4315d0813573a2d8faee361 # v7.1.1
        with:
          files: |
            **/*.{md,yaml,yml}
          config: '.github/workflows/utils/cspell.json'
