name: Spell Check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run cSpell
        uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8.4.0
        with:
          incremental_files_only: false
          use_cspell_files: true
          config: '.github/workflows/utils/cspell.json'
