name: Weekly Slack report

on:
  schedule:
    - cron: "0 10 * * 4"  # Thursdays 10:00 UTC
  workflow_dispatch:

permissions: read-all

jobs:
  report:
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'open-telemetry'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: .github/workflows/scripts
          persist-credentials: false
      - name: Run weekly-slack-report.sh
        run: ./.github/workflows/scripts/weekly-slack-report.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
