name: Zizmor

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '44 17 * * 1' # weekly at 17:44 UTC on Monday
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    permissions:
      contents: read # for actions/checkout
      security-events: write # for zizmor to upload SARIF results
    uses: open-telemetry/shared-workflows/.github/workflows/zizmor.yml@dde3047a8f219c296772c17936b9d02bb7447af5 # v0.12.0