name: Zizmor

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '44 17 * * 1' # weekly at 17:44 UTC on Monday
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    permissions:
      contents: read # for actions/checkout
      security-events: write # for zizmor to upload SARIF results
    uses: open-telemetry/shared-workflows/.github/workflows/zizmor.yml@ad1959372f2919fcf2556d3a3d12ed5265c54209 # v0.16.0